site_name: NAUTI
repo_name: nauti-netdev
repo_url: https://github.com/nauti-netdev
theme:
  name: material
  palette:
    primary: cyan
    accent: light green
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nwkautomaniac
    - icon: fontawesome/brands/github
      link: https://github.com/nauti-netdev
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Installation: installation.md
  - Sources:
    - nauti-ipfabric: sources/nauti-ipfabric.md
    - nauti-netbox: sources/nauti-netbox.md
    - nauti-clearpass: sources/nauti-clearpass.md
